export enum MessageEnum {
    SMSUrl='http://apir.int.amdtelecom.net/sms',
    CompaingUrl='http://apir.int.amdtelecom.net/sms/campaign',
    VoiceUrl='http://apir.int.amdtelecom.net/voice/campaign',
    ViberUrl='http://apir.int.amdtelecom.net/viber/campaign',
    ShortenUrl='http://apir.int.amdtelecom.net/shorten',
    Base64Token='NjEwN2ZlODIyMDliYjQwMDAxNWJhMmE3OjJKeGp4UmFnUmU=',
    Base64TokenInsufficientBalance='',
    EmptyParam='',
    ValidMessage='TestMessage',
    ValidPhone='+375298603938',
    FirstVN='+12012560718',
    SecondVN='14104490875',
    ValidSender='TestSender',
    ValidQueuedStatus='Queued',
    ValidTokenType='bearer',
    ValidStrategyType='OnCompletion',
    ValidGroup='New',
    USLanguageCode='en-US',
    GRLanguageCode='el-GR',
    UnicodeProperty='unicode',
    TrackingIDProperty='trackingId',
    CreatedAtProperty='createdAt',
    urlShortener='https://webhook.site/02583cd1-6f2f-4bd2-aa98-7baa4a7bd888',
    urlDTMF='http://www.externalharddrive.com/waves/animal/duck.wav',
    imageURL='https://www.w3schools.com/css/paris.jpg',
    targetUrl='https://www.routee.net/',
    TranscodeMessage='ΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέρα',
    UnTranscodeMessage='KAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPA',
    Status200=200,
    Status400=400,
    Status401=401,
    InvalidPhone='+3752986039380000',
    InvalidBalanceCode='400001009',
    InvalidBalanceMessage='Insufficient Balance',
    InvalidTokenMessage='invalid_token',
    InvalidSenderCode='400005000',
    InvalidFieldCode='400000000',
    InvalidBase64TokenError= 'Unauthorized',
    InvalidBase64TokenMessage= 'Full authentication is required to access this resource',

    ShortenLong_url='https://www.somereallybigurlthisisnottobigbutok.com',
    ShortenValidity='12345',
    ShortenDomain='sends.ms',
    ShortenCallbackUrl='callbackUrl'
}