export enum MessageEnum {
    Base64Token='NjEwN2ZlODIyMDliYjQwMDAxNWJhMmE3OjJKeGp4UmFnUmU=',
    Base64TokenInsufficientBalance='',
    EmptyParam='',
    ValidMessage='TestMessage',
    ValidPhone='+375298603938',
    ValidSender='TestSender',
    ValidQueuedStatus='Queued',
    ValidTokenType='bearer',
    UnicodeProperty='unicode',
    TrackingIDProperty='trackingId',
    CreatedAtProperty='createdAt',
    urlShortener='https://webhook.site/02583cd1-6f2f-4bd2-aa98-7baa4a7bd888',
    TranscodeMessage='ΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέραΚαλησπέρα',
    UnTranscodeMessage='KAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPAKAΛHΣΠEPA',
    Status200=200,
    Status400=400,
    Status401=401,
    InvalidPhone='+3752986039380000',
    InvalidBalanceCode='400001009',
    InvalidBalanceMessage='Insufficient Balance',
    InvalidTokenMessage='invalid_token',
    InvalidSenderCode='400005000',
    InvalidFieldCode='400000000',
    InvalidBase64TokenError= 'Unauthorized',
    InvalidBase64TokenMessage= 'Full authentication is required to access this resource',
}